MeetingApp/MeetingApp/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeetingApp.Controllers
{
    [Authorize(Roles = "E, BE, A, LA")]
    public class EventsController : Controller
    {
        // GET: Events
        public ActionResult Index()
        {
            return View();
        }
    }
}

MeetingApp/MeetingApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MeetingApp.DAL;
using PagedList.Mvc;
using PagedList;

namespace MeetingApp.Controllers
{
    public class HomeController : Controller
    {
        private WPG_ConferenceEntities _db;
        public HomeController()
        {
            _db = new WPG_ConferenceEntities();
        }
        public ActionResult Index(int? page)
        {
            var emp = _db.Employees.Include(x => x.Employee_Guest).Include(x => x.Meeting_Employee).Include(x => x.Role).ToList();
            return View(emp.OrderByDescending(x => x.Meeting_Employee.Count > 0).ToPagedList(page??1,20));
        }


    }
}

MeetingApp/MeetingApp/Controllers/MeetingController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MeetingApp.DAL;

namespace MeetingApp.Controllers
{
    public class MeetingController : Controller
    {

        private WPG_ConferenceEntities _db;
        public MeetingController()
        {
            _db = new WPG_ConferenceEntities();
        }
        // GET: Meeting
        public PartialViewResult EmployeeMeetings(int? empId )
        {
            var empMeeting = _db.Meeting_Employee.Where(x => x.Employee_Id == empId).Select(x => x.Meeting).ToList();
            return PartialView(empMeeting);
        }

        public PartialViewResult MeetingDetails(int? meetingId)
        {
            var meetingInfo = _db.Meetings.Find(meetingId);
            return PartialView(meetingInfo);
        }
    }
}

MeetingApp/MeetingApp/Controllers/MeetingNoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeetingApp.Controllers
{
    public class MeetingNoteController : Controller
    {
        // GET: MeetingNote
        public ActionResult Index()
        {
            return View();
        }
    }
}

MeetingApp/MeetingApp/Controllers/SchedulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MeetingApp.DAL;

namespace MeetingApp.Controllers
{
    [Authorize(Roles = "E, BE, A, LA")]
    public class SchedulesController : Controller
    {
        // GET: Schedules
        public ActionResult Index()
        {
            return View();
        }
    }
}

MeetingApp/MeetingApp/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MeetingApp.DAL;

namespace MeetingApp.Controllers
{
    [AllowAnonymous]
    public class SecurityController : Controller
    {
        // GET: Security
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Employee employee)
        {
            if (Membership.ValidateUser(employee.Email, employee.Password))
            {
                FormsAuthentication.SetAuthCookie(employee.Email, false);
                return RedirectToAction("Index", "Home");
            }

            TempData["Msg"] = "Login Failed, please try again";
            return View();
        }
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

MeetingApp/MeetingApp/Views/Events/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Welcome to events page</h2>

MeetingApp/MeetingApp/Views/Home/Index.cshtml
@model IPagedList<MeetingApp.DAL.Employee>
@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Home Page";
}
@section Scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <script type="text/javascript">

        function ClearMeetingDetails() {
            $('#meetingDetails').replaceWith(' <div id="meetingDetails"></div> ');
        }

    </script>
}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Welcome To Meeting Scheduling System</h3>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-hover table-bordered table-condensed table-responsive ">
                        <tbody>
                            @foreach (var emp in Model)
                            {

                                <tr>
                                    <td>
                                        @Ajax.ActionLink(emp.Email, "EmployeeMeetings", "Meeting",new { empId = emp.Id},
                                            new AjaxOptions
                                            {
                                                HttpMethod = "GET", // HttpMethod to use, GET or POST
                                                UpdateTargetId = "empMeeting", // ID of the HTML element to update
                                                InsertionMode = InsertionMode.Replace // Replace the existing contents
                                            }, new{onclick = "ClearMeetingDetails()" }) @*&nbsp; Guest: <span class="badge">@emp.Employee_Guest.Count</span>*@ &nbsp; Meeting: <span class="badge">@emp.Meeting_Employee.Count</span>
                                        </td>
                                    </tr>
                                }
                        </tbody>
                    </table>
                </div>
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded})
            </div>
        </div>
        <div class="col-md-4">

            <div id="empMeeting">

            </div>
        </div>
        <div class="col-md-4">
            <div id="meetingDetails">

            </div>
        </div>
    </div>


</div>

MeetingApp/MeetingApp/Views/Meeting/EmployeeMeetings.cshtml
@model List<MeetingApp.DAL.Meeting>

@if (Model.Count > 0)
{
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Employee Meetings Info</h3>
        </div>
        <div class="panel-body">
            <table class="table table-striped table-hover ">
                <thead>
                    <tr>
                        <th>Topic</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var meeting in Model)
                    {
                        <tr>
                            <td>
                                @Ajax.ActionLink(meeting.Topic, "MeetingDetails", "Meeting",new { meetingId = meeting.Id},
                                    new AjaxOptions
                                    {
                                        HttpMethod = "GET", // HttpMethod to use, GET or POST
                                        UpdateTargetId = "meetingDetails", // ID of the HTML element to update
                                        InsertionMode = InsertionMode.Replace // Replace the existing contents
                                    })
                            </td>
                            <td>@meeting.Meeting_Date.ToShortDateString()</td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
}
else
{
    <div class="alert alert-dismissible alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Heads up!</strong> No meetings found for this user.
    </div>
}

MeetingApp/MeetingApp/Views/Meeting/MeetingDetails.cshtml
@model MeetingApp.DAL.Meeting

@if (Model != null)
{
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">Meeting Details</h3>
        </div>
        <div class="panel-body">
            <ul class="list-group">
                <li class="list-group-item">
                    <i class="glyphicon glyphicon-info-sign" style="color: red"></i> <strong>Topic: </strong>@Model.Topic
                </li>
                <li class="list-group-item">
                    <i class="glyphicon glyphicon-calendar" style="color: blue"></i> <b>Date: </b> @Model.Meeting_Date.ToShortDateString()
                </li>
                <li class="list-group-item">
                    <i class="glyphicon glyphicon-bell " style="color: green"></i>  <strong>Type: </strong> @Model.MeetingType.meeting_type
                </li>
            </ul>
        </div>
    </div>
}
else
{
    <div class="alert alert-dismissible alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Heads up!</strong> No meetings found for this user.
    </div>
}

MeetingApp/MeetingApp/Views/Schedules/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Weclome to your schedule</h2>

MeetingApp/MeetingApp/Views/Security/Login.cshtml
@model MeetingApp.DAL.Employee

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@if (TempData["Msg"] != null)
{
    <h4 style="color: red">@TempData["Msg"].ToString()</h4>
}

@using (Html.BeginForm("Login","Security", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Weclome to Login page</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

MeetingApp/MeetingApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IC-Start Scheduler</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pull-left">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {

                        if (User.IsInRole("E"))
                        {
                            <li>@Html.ActionLink("Schedules", "Index", "Schedules")</li>

                        }
                        <li>@Html.ActionLink("Events", "Index", "Events")</li>


                        <li>@Html.ActionLink("LogOut", "LogOut", "Security")</li>

                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Security")</li>
                    }

                </ul>
                
                <ul class="nav navbar-nav pull-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                    <li class="pull-right"><a href="#"><b>Welcome</b> @User.Identity.Name</a></li>
                    }
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid body-content" style="margin-top: 20px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meeting Scheduling System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>